// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbqfucofucluahcpgzbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImticWZ1Y29mdWNsdWFoY3BnemJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjUxNTgsImV4cCI6MjA2MDc0MTE1OH0.X3cNJM-vAshBut3aCsDcHPCir_UV22Gd3kgwgtFQyBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);